version: "3.9"

services:
  build:
    image: maip-build
    build:
      context: .
      dockerfile: Dockerfile.build
  start:
    image: maip-start
    build:
      context: .
      dockerfile: Dockerfile.start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
